//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub use super::access::Entity as Access;
pub use super::app::Entity as App;
pub use super::app_user::Entity as AppUser;
pub use super::resource::Entity as Resource;
pub use super::role::Entity as Role;
pub use super::user::Entity as User;
pub use super::user_role::Entity as UserRole;
