//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "status")]
pub enum Status {
    #[sea_orm(string_value = "ok")]
    Ok,
    #[sea_orm(string_value = "disabled")]
    Disabled,
    #[sea_orm(string_value = "applying")]
    Applying,
    #[sea_orm(string_value = "deny")]
    Deny,
}
