//
// Copyright (C) 2024 veypi <i@veypi.com>
// 2024-09-20 16:10:16
// Distributed under terms of the MIT license.
//
// Auto generated by OneBD. DO NOT EDIT

package api

import (
	"github.com/veypi/OneBD/rest"
	"oa/api/access"
	"oa/api/app"
	"oa/api/role"
	"oa/api/user"
)

func Use(r rest.Router) {
	access.Use(r.SubRouter("access"))
	app.Use(r.SubRouter("app"))
	role.Use(r.SubRouter("role"))
	user.Use(r.SubRouter("user"))
}
