// Code generated by goctl. DO NOT EDIT.

export interface AppReq {
	password: string
}
export interface AppReqParams {
	username: string
}

export interface AppResp {
	id: number
	name: string
	token: string
	expireAt: string
}

export interface LoginReqParams {
	pwd: string
	client: string
	typ: string
}

export interface RegReq {
	username: string
	pwd: string
}

export interface AuthHeaders {
	authorization: string
}



export interface UserResp {
	id: string
	created: number
	updated: number
	username: string
	nickname: string
	email: string
	phone: string
	icon: string
	status: number // 状态（0：ok，1：disabled）
	used: number
	space: number
}

