//
// Copyright (C) 2024 veypi <i@veypi.com>
// 2024-09-24 22:37:12
// Distributed under terms of the MIT license.
//
// Auto generated by OneBD. DO NOT EDIT

package token

import (
	"github.com/veypi/OneBD/rest"
)

func Use(r rest.Router) {
	useToken(r)
}
