//
// Copyright (C) 2024 veypi <i@veypi.com>
// 2024-09-23 16:28:13
// Distributed under terms of the MIT license.
//
// Auto generated by OneBD. DO NOT EDIT

package app

import (
	"github.com/veypi/OneBD/rest"
)

func Use(r rest.Router) {
	useApp(r)
	useAppUser(r.SubRouter(":app_id/app_user"))
	useResource(r.SubRouter(":app_id/resource"))
}
