// Code generated by goctl. DO NOT EDIT.
package types

type AppReq struct {
	Error
	Appname  string `json:"username"`
	Password string `json:"password"`
}

type AppResp struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Token    string `json:"token"`
	ExpireAt string `json:"expireAt"`
}

type LoginReq struct {
	Error
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Token    string `json:"token"`
	ExpireAt string `json:"expireAt"`
}

type Error struct {
	Status string `json:"status"`
	Code   int    `json:"code"`
}
