// Code generated by goctl. DO NOT EDIT.
package types

type AppReq struct {
	Appname  string `json:"username"`
	Password string `json:"password"`
	Pas      string `query:"pas"`
	Pa       string `path:"pa"`
}

type AppResp struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Token    string `json:"token"`
	ExpireAt string `json:"expireAt"`
}

type LoginReq struct {
	Id     string `path:"id"`
	Client string `json:"client"`
	Pwd    string `json:"pwd"`
	Typ    string `json:"typ,optional"`
}

type RegReq struct {
	Username string `json:"username"`
	Pwd      string `json:"pwd"`
}

type Auth struct {
	Authorization string `header:"authorization"`
}

type GetReq struct {
	Id int64 `path:"id"`
}

type ListReq struct {
	Username string `query:"username"`
}

type UserResp struct {
	Id       string `json:"id"`
	Created  uint   `json:"created"`
	Updated  uint   `json:"updated"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Icon     string `json:"icon"`
	Status   int64  `json:"status"` // 状态（0：ok，1：disabled）
	Used     int64  `json:"used"`
	Space    int64  `json:"space"`
}
